language: node_js
node_js: stable
install:
  - npm ci
cache:
  directories:
    - "$Home/.npm" 
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: main
