language: node_js
node_js: stable

cache: 
directories:
  - node_modules
before_deploy:
  - "npm install"

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: main
