language: node_js
node_js: stable

cache: npm
directories:
  - node_modules
script:
  - npm install
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: main
